site_name: ARY
site_description: Ary documentation
site_url: https://sitename.example
theme:
  name: material
  palette:
  # Dark mode
  - scheme: slate
    primary: blue grey
    accent: deep purple
  features:
    - navigation.instant # instant loading feature from links click, req site_url to be set
    - navigation.instant.prefetch # prefetch if hoover over link
    - navigation.instant.progress # show progress of loading
    - navigation.tracking # right side real time navigation
    - navigation.tabs # top menu
    - navigation.tabs.sticky # top menu visible even if scrolling
    #- navigation.sections # left tabs menu
    - toc.follow # right menu follow

plugins:
  - search

extra_css:
  - css/neoteroi-mkdocs.css

markdown_extensions:
  - neoteroi.timeline

nav:
  - Home: index.md
  - Wiki:
      - Essentials:
          - Lore: pages/lore.md   
          - Controls: pages/controls.md
          - Skills: pages/skills.md
          - Crafting: pages/crafting.md
          - Quests: pages/quests.md
          - Enemies: pages/enemies.md
          - Death: pages/death.md 
          - Special effects: pages/special_effects.md
  - Roadmap: pages/roadmap.md
  - About: pages/about.md